### ISSUE TITLE
ValueError: API request failed with: Invalid API Key

### ISSUE THREAD

**Issue by gayatri9213** [PatrickAlphaC/defi-stake-yield-brownie#6]
I am getting this error after runnig " brownie run scripts/deploy.py --network kovan " this command

**Comment by PatrickAlphaC** [comment]
Could you send me the full output and log? And steps you took to get here?

**Comment by gayatri9213** [comment]
![Screenshot from 2022-03-01 09-46-12](https://user-images.githubusercontent.com/88524438/156103922-00e56ca5-96a8-4eda-b81a-239397376806.png)

**Comment by gayatri9213** [comment]
We've added environment variables to the `.env` file and the tried to run " brownie run scripts/deploy.py --network kovan
 " this command

**Comment by PatrickAlphaC** [comment]
In the future, if you could copy-paste your issues instead of screenshots, and format them with three backticks ``` that would be better since they will be searchable easier and people who want to help you will be able to copy your error and look around too. Thanks.

Also *I HOPE THAT YOUR PRIVATE KEY DOESNT HAVE ANY REAL MONEY ASSOCIATED WITH IT*. If it does, it's compromised, please move your money immediately. 

And finally, your Etherscan token is your etherscan API key, not a URL to etherscan. Go here and select a free plan to get an API key: https://etherscan.io/apis
