### ISSUE TITLE
Re-Entrancy 

### ISSUE THREAD

**Issue by railBitsAndHex** [PatrickAlphaC/defi-stake-yield-brownie#8]
Hi, may I know if there a possibility of reentrancy in ` stakeTokens(uint256 _amount, address token)` and `unstakeTokens(address token)` function as `transfer` and `transferFrom` function is called before update of `stakingBalance`?

**Comment by PatrickAlphaC** [comment]
There is :D

**Comment by railBitsAndHex** [comment]
Thanks for the update!
